import "server-only";

import {
  assertSafeKey,
  type FileStorage,
  type PutFileInput,
  type StoredObject,
} from "@/server/storage/types";

/**
 * Certificate files in Supabase Storage. The production implementation.
 *
 * ## Why this exists
 *
 * The local driver writes to a directory, which is correct for development and
 * wrong for anywhere the application runs as more than one process. A file
 * written to one instance's disk is unreadable from the next and gone at the
 * following deploy, so on any serverless or replicated host the local driver
 * does not merely degrade — it loses business documents silently, which for an
 * airworthiness certificate is the worst available failure.
 *
 * ## Why there is no SDK here
 *
 * `FileStorage` is four operations keyed by an opaque string. `@supabase/
 * supabase-js` brings PostgREST, Realtime, and an auth client to serve them,
 * none of which this application wants — it already has Prisma for data and
 * Clerk for identity, and a second client library holding a second set of
 * credentials is a second thing to keep correct. The Storage REST API is
 * documented, stable, and reachable with `fetch`, so that is what this uses.
 *
 * ## What must be true of the bucket
 *
 * **It must be private.** Not a recommendation — the security property this
 * whole subsystem rests on. A public bucket makes every certificate readable by
 * anyone who learns its object path, which is exactly what the authenticated
 * download route exists to prevent, and it would do so without any code here
 * changing or failing. `FileStorage` deliberately has no `url` method and this
 * driver mints no signed URLs, so the only way bytes reach a browser remains
 * `GET /api/certificates/{id}/file` with a session behind it.
 *
 * ## Credentials
 *
 * The service-role key bypasses row-level security, which is why it is asked
 * for: this driver acts as the application, not as an end user, and the
 * application has already decided the caller may have the file. It is read
 * through `src/lib/env.ts`, which is `server-only`, and its name carries no
 * `NEXT_PUBLIC_` prefix, so it cannot reach a browser bundle. It is never
 * logged — see `describeFailure`, which reports status codes and keys and
 * never headers.
 *
 * ## Keys
 *
 * Unchanged. A key is still `certificates/<uuid>.<ext>`, generated by
 * `certificateStorageKey`, and it is used verbatim as the object path. The
 * files already on a developer's disk therefore carry over to a bucket without
 * being renamed, and `assertSafeKey` runs here exactly as it does in the local
 * driver — a key is a URL path segment here rather than a filesystem path, and
 * `..` is meaningful in both.
 */

export interface SupabaseStorageConfig {
  /** The project URL, e.g. `https://abcdefgh.supabase.co`. No trailing slash. */
  url: string;
  /** Service-role key. Server-side only, never `NEXT_PUBLIC_`. */
  serviceRoleKey: string;
  /** The private bucket certificates live in. */
  bucket: string;
}

/**
 * The subset of `fetch` this driver uses.
 *
 * Injected rather than reached for globally so the tests can drive every branch
 * — a 404, a 500, a network failure — against a fake instead of a real project.
 * Production passes nothing and gets the platform's `fetch`.
 */
export type FetchLike = (
  input: string,
  init?: {
    method?: string;
    headers?: Record<string, string>;
    body?: Uint8Array | string;
  },
) => Promise<{
  ok: boolean;
  status: number;
  arrayBuffer(): Promise<ArrayBuffer>;
  text(): Promise<string>;
  headers: { get(name: string): string | null };
}>;

export class SupabaseFileStorage implements FileStorage {
  readonly name = "supabase";

  private readonly url: string;
  private readonly serviceRoleKey: string;
  private readonly bucket: string;
  private readonly fetchImpl: FetchLike;

  constructor(config: SupabaseStorageConfig, fetchImpl?: FetchLike) {
    // Trailing slashes would produce `//storage/v1/...`, which some proxies
    // normalise and others do not. Normalising once here means every URL built
    // below is built the same way.
    this.url = config.url.replace(/\/+$/, "");
    this.serviceRoleKey = config.serviceRoleKey;
    this.bucket = config.bucket;
    this.fetchImpl = fetchImpl ?? (globalThis.fetch as unknown as FetchLike);
  }

  /**
   * The REST address of one object.
   *
   * Each segment of the key is percent-encoded separately, so the slashes that
   * separate folders survive and anything else that would change the meaning of
   * the path does not. `assertSafeKey` has already refused `..`, a leading
   * slash and every character outside a conservative set; this is the second
   * check, for the same reason the local driver resolves and compares paths
   * after its own — the two fail for different reasons and the cost of being
   * wrong is reading somebody else's object.
   */
  private objectUrl(key: string): string {
    assertSafeKey(key);

    const path = key
      .split("/")
      .map((segment) => encodeURIComponent(segment))
      .join("/");

    return `${this.url}/storage/v1/object/${encodeURIComponent(this.bucket)}/${path}`;
  }

  /**
   * Both headers, deliberately. Supabase's gateway routes on `apikey` and the
   * storage service authorises on `Authorization`; sending only one works
   * against some deployments and not others.
   */
  private authHeaders(): Record<string, string> {
    return {
      apikey: this.serviceRoleKey,
      Authorization: `Bearer ${this.serviceRoleKey}`,
    };
  }

  async put({ key, body, contentType }: PutFileInput): Promise<void> {
    const response = await this.fetchImpl(this.objectUrl(key), {
      method: "POST",
      headers: {
        ...this.authHeaders(),
        "Content-Type": contentType,
        // The contract says put replaces. Without this a repeated key is a 409,
        // and callers would have to care about a distinction storage made up.
        "x-upsert": "true",
      },
      // A fresh `Uint8Array` over the same bytes: `Buffer`'s backing store is
      // typed `ArrayBufferLike`, which `BodyInit` will not accept.
      body: new Uint8Array(body),
    });

    if (!response.ok) {
      throw new Error(await describeFailure("store", key, response));
    }
  }

  async get(key: string): Promise<StoredObject | null> {
    const response = await this.fetchImpl(this.objectUrl(key), {
      method: "GET",
      headers: this.authHeaders(),
    });

    // Missing is not an error — the contract says so, and `getCertificateFile`
    // turns the null into a message about a row whose bytes did not survive.
    if (isMissing(response.status)) return null;

    if (!response.ok) {
      throw new Error(await describeFailure("read", key, response));
    }

    const body = Buffer.from(await response.arrayBuffer());

    return {
      body,
      /*
       * Reported for completeness, not relied upon. `getCertificateFile` serves
       * the type recorded on the certificate row when the bytes were sniffed on
       * upload, which is the only value in the system that was actually checked
       * against the file. Storage's opinion is never sent to a browser.
       */
      contentType:
        response.headers.get("content-type") ?? "application/octet-stream",
      size: body.byteLength,
    };
  }

  /**
   * Removes an object, and treats an absent one as done.
   *
   * The bulk form — a `prefixes` array against the bucket — because that is the
   * documented delete endpoint. One key at a time is all this application ever
   * needs, and a batch API called with one element is simpler than a second
   * code path.
   */
  async delete(key: string): Promise<void> {
    const response = await this.fetchImpl(
      `${this.url}/storage/v1/object/${encodeURIComponent(this.bucket)}`,
      {
        method: "DELETE",
        headers: { ...this.authHeaders(), "Content-Type": "application/json" },
        // Validated before it is sent, exactly as `objectUrl` would.
        body: JSON.stringify({ prefixes: [assertedKey(key)] }),
      },
    );

    /*
     * Deleting what is already gone must succeed. Callers use `delete` to clean
     * up after a failed upload, and a cleanup that throws when there was
     * nothing to clean turns one problem into two — the local driver passes
     * `force` for the same reason.
     */
    if (isMissing(response.status)) return;

    if (!response.ok) {
      throw new Error(await describeFailure("delete", key, response));
    }
  }

  async exists(key: string): Promise<boolean> {
    const response = await this.fetchImpl(this.objectUrl(key), {
      method: "HEAD",
      headers: this.authHeaders(),
    });

    if (isMissing(response.status)) return false;

    if (!response.ok) {
      throw new Error(await describeFailure("check", key, response));
    }

    return true;
  }
}

/** `assertSafeKey` as an expression, for use inside a payload. */
function assertedKey(key: string): string {
  assertSafeKey(key);
  return key;
}

/**
 * The statuses that mean "no such object".
 *
 * 404 is the honest one. 400 is included because Supabase Storage answers a
 * missing object on some routes with a 400 carrying `{"error":"not_found"}`,
 * and treating that as a fault would make an ordinary absent file throw out of
 * `get` instead of returning null.
 */
function isMissing(status: number): boolean {
  return status === 404 || status === 400;
}

/**
 * A failure message safe to log.
 *
 * The key and the status go in; the request headers never do, because they
 * carry the service-role key and this string ends up in `console.error` by way
 * of `toSafeError`. The response body is included because Supabase puts a
 * useful reason there, and truncated because it is remote input.
 */
async function describeFailure(
  verb: string,
  key: string,
  response: { status: number; text(): Promise<string> },
): Promise<string> {
  let detail = "";

  try {
    detail = (await response.text()).slice(0, 200);
  } catch {
    // A body that cannot be read is not worth a second failure.
  }

  return `Supabase Storage could not ${verb} ${JSON.stringify(key)} (HTTP ${response.status})${
    detail ? `: ${detail}` : ""
  }`;
}
