/**
 * The file-storage contract.
 *
 * Deliberately tiny, and deliberately not a filesystem. Four operations — put,
 * get, delete, exists — keyed by an opaque string, each of which S3, Supabase
 * Storage, Cloudinary, Azure Blob and a local directory can all implement
 * without contortion. Anything richer (directory listing, renaming, partial
 * reads, signed URLs) would be a feature of one provider that the others have
 * to fake, and the abstraction would start leaking the day someone used it.
 *
 * What the contract deliberately does *not* include is a URL. A storage layer
 * that hands out URLs is a storage layer whose files are reachable by anyone
 * holding one, and certificates are business documents that must not be. Bytes
 * come back through `get` and are served by an authenticated route handler that
 * checks the session first; the only address a browser ever sees is
 * `/api/certificates/{id}/file`, which resolves to a key server-side.
 *
 * Keys are generated by this application, never derived from a user-supplied
 * filename. An implementation must still validate the key it is given before
 * using it — see `assertSafeKey` — because a key that reaches a filesystem is a
 * path, and `../` is a valid string.
 */

export interface PutFileInput {
  key: string;
  body: Buffer;
  /** The type determined by inspecting the bytes, never the browser's claim. */
  contentType: string;
}

export interface StoredObject {
  body: Buffer;
  contentType: string;
  size: number;
}

export interface FileStorage {
  /** Identifies the driver in logs and on the settings page. */
  readonly name: string;

  /**
   * Writes an object. Overwriting an existing key is not a scenario this
   * application creates — keys are unique per upload — but implementations
   * should treat it as replace rather than error.
   */
  put(input: PutFileInput): Promise<void>;

  /** The object, or null if the key does not exist. Missing is not an error. */
  get(key: string): Promise<StoredObject | null>;

  /**
   * Removes an object. Deleting a key that is already gone must succeed:
   * callers use this to clean up after a failure, and a cleanup that throws
   * when there was nothing to clean turns one problem into two.
   */
  delete(key: string): Promise<void>;

  exists(key: string): Promise<boolean>;
}

/**
 * The shape of every key this application generates:
 * `certificates/<cuid>.<ext>` — a folder, an unguessable id, an extension.
 *
 * Enforced rather than assumed. A key is a path once it reaches a filesystem
 * and a prefix once it reaches a bucket, so anything containing `..`, a
 * backslash, a leading slash or a character outside this set is refused before
 * it can be resolved against a root directory.
 */
const SAFE_KEY = /^[a-z0-9][a-z0-9._-]*(\/[a-z0-9][a-z0-9._-]*)*$/i;

export function assertSafeKey(key: string): void {
  if (!key || key.length > 512 || key.includes("..") || !SAFE_KEY.test(key)) {
    throw new Error(`Unsafe storage key: ${JSON.stringify(key)}`);
  }
}
